platform: linux

image_resource:
  type: docker-image
  source:
    repository: ruby
    tag: 2.3.0

inputs:
- name: flight-school

run:
  path: ./flight-school/ci/test1.sh
  path: ./flight-school/ci/test2.sh
