resources:
- name: pipeline-code
  type: git
  source:
    uri: https://github.com/nikozl/tests

- name: every-20m
  type: time
  source:
    interval: 20m

jobs:
- name: job-generate-and-pass-file
  public: true
  plan:
  - get: pipeline-code
    trigger: true
  - get: every-20m
    trigger: true
  - task: generate-file
    file: pipeline-code/tasks/task_generate_file.yml
  - task: show-file
    file: pipeline-code/tasks/task_show_file.yml

- name: job-confirm
  public: true
  plan:
  - get: pipeline-code
    trigger: true
    passed: [job-generate-and-pass-file]
  - task: say-done
    file: pipeline-code/tasks/task_say_done.yml

- name: new-job
  public: true
  plan:
  - get: pipeline-code
    trigger: true
    passed: [job-confirm]
  - task: job-niko
    file: pipeline-code/tasks/task_job_niko.yml
