resources:
- name: pipeline-code
  type: git
  source:
    uri: https://github.com/nikozl/tests
- name: every-2m
  type: time
  source:
    interval: 2m

jobs:
- name: job-generate-and-pass-file
  public: true
  plan:
  - get: pipeline-code
    trigger: true
  - get: every-30m
    trigger: true
  - task: generate-file
    file: pipeline-code/niko/task_generate_file.yml
  - task: show-file
    file: pipeline-code/niko/task_show_file.yml

- name: job-confirm-previous-is-done
  public: true
  plan:
  - get: pipeline-code
    trigger: true
    passed: [job-generate-and-pass-file]
  - task: say-done
    file: pipeline-code/niko/task_say_done.yml

- name: job-niko
  public: true
  plan:
  - get: pipeline-code
    trigger: true
    passed: [job-confirm-previous-is-done]
  - task: update-files
    file: pipeline-code/niko/task_update_files.yml
