resources:
- name: pipeline-code
  type: git
  source:
    uri: https://github.com/nikozl/tests

jobs:
- name: job-generate-file
  public: true
  plan:
  - get: pipeline-code
    trigger: true
  - task: generate-file
    file: pipeline-code/tasks/task_generate_file.yml

- name: job-pass-file
  public: true
  plan:
  - get: pipeline-code
  - get: generate_file_output 
    trigger: true
    passed: [job-generate-file]
  - task: show-file
    file: pipeline-code/tasks/task_show_file.yml
