platform: linux

image_resource:
  type: docker-image
  source:
      repository: hashicorp/packer

inputs:
- name: tests

outputs:
- name: /tmp/files/output-qemu

run:
  path: tests/packer-mkosi_build.sh

