platform: linux

image_resource:
  type: docker-image
  source: {repository: eeacms/scp-server}

inputs:
- name: pipeline-code
- name: generate_file_output

run:
  path: pipeline-code/scripts/show_files.sh

