resources:
- name: tests
  type: git
  source:
    uri: https://github.com/nikozl/tests 
    branch: master


jobs:
- name: test-git
  plan:
  - get: tests
    trigger: true
  - task: testeo
    file: tests/build.yml

- name: test-dos-git
  plan:
  - get: tests
    trigger: true
  - task: testeo-dos
    file: tests/build2.yml
