resources:
- name: git_test
  type: git
  source:
    uri: https://github.com/nikozl/tests 
    branch: master

jobs:
- name: test-git
  plan:
  - get: git_test
    trigger: true
  - task: testeo
    file: tests/build.yml
